#!/bin/bash

logdir=$(dirname $(readlink $0))

echo "generate log for $repo"
repo=`basename $PWD`
log="$logdir/$repo.log"
[[ -e $log ]] && rm -v $log
git log --author='Patrick' --all --oneline --pretty=tformat:'%ci#%h#%s' | sed "s:\$:#$repo:g" > $log

echo "cat and sort all repo-logfiles"
fullog=$logdir/full.log
[[ -e $fullog ]] && rm -v $fullog
cat $logdir/*.log | sort -r >> $fullog

echo "generate commits.yml"
commits=$logdir/commits.yml
[[ -e $commits ]] && rm -v $commits
while read commit; do
  IFS='#' read stamp sha1 line name <<<$commit
  echo -e "- name: \"$name\"\n  time: \"$stamp\"" >> $commits
  echo -e "  sha1: \"$sha1\"\n  line: \"$line\"\n" >> $commits
done < $fullog
rm -v $fullog

#echo "commit logs for $repo"
#cd $logdir
#git add $log $commits
#git commit -m "update $repo logs"

exit 0
