#!/bin/bash

logdir=$(dirname $(readlink $0))

# generate log file (commit one-liners) for current repo
repo=`basename $PWD`
log="$logdir/$repo.log"
[[ -e $log ]] && rm -v $log
git log --author='Patrick' --all --oneline --pretty=tformat:'%ci#%h#%s' | sed "s:\$:#$repo:g" > $log

# cat and sort all repo-logfiles
fullog=$logdir/full.log
[[ -e $fullog ]] && rm -v $fullog
cat $logdir/*.log | sort -r >> $fullog

# generate commits.yml
commits=$logdir/commits.yml
[[ -e $commits ]] && rm -v $commits
while read commit; do
  IFS='#' read stamp sha1 line name <<<$commit
  echo -e "- name: \"$name\"\n  time: \"$stamp\"" >> $commits
  echo -e "  sha1: \"$sha1\"\n  line: \"$line\"\n" >> $commits
done < $fullog
rm -v $fullog

# commit and push changes
#cd $logdir
#git add .
#git commit -m "update $repo logs"
#git push

exit 0
